
String? getCountryWithIso(String iso){
  if(countryIso.containsKey(iso)){
    return countryIso[iso];
  }
  return "";
}

Map<String, String> countryIso = {
  "af":"Afghanistan",
  "al":"Albanie",
  "dz":"Algérie",
  "as":"Samoa Américaine ",
  "ad":"Andorre",
  "ao":"Angola",
  "ai":"Anguilla",
  "aq":"Antarctique",
  "ag":"Antigua and Barbuda",
  "ar":"Argentine",
  "am":"Arménie",
  "aw":"Aruba",
  "au":"Australie",
  "at":"Autriche",
  "az":"Azerbaïdjan",
  "bs":"Bahamas",
  "bh":"Bahreïn",
  "bd":"Bangladesh",
  "bb":"Barbade",
  "by":"Biélorussie",
  "be":"Belgique",
  "bz":"Belize",
  "bj":"Benin",
  "bm":"Bermude",
  "bt":"Bhoutan",
  "bo":"Bolivie",
  "bq":"Pays-Bas caribéens",
  "ba":"Bosnie-Herzégovine",
  "bw":"Botswana",
  "bv":"Île Bouvet",
  "br":"Brésil",
  "io":"Territoire britannique de l'océan Indien",
  "bn":"Brunei Darussalam",
  "bg":"Bulgarie",
  "bf":"Burkina Faso",
  "bi":"Burundi",
  "cv":"Cap Vert",
  "kh":"Cambodge",
  "cm":"Cameroun",
  "ca":"Canada",
  "ky":"Iles Caïmans",
  "cf":"Republique Central d'Afrique ",
  "td":"Tchad",
  "cl":"Chilie",
  "cn":"Chine",
  "cx":"Île Christmas",
  "cc":"Îles Cocos",
  "co":"Colombie",
  "km":"Comores",
  "cd":"République Démocratique du Congo",
  "cg":"Congo",
  "ck":"Îles Cook",
  "cr":"Costa Rica",
  "hr":"Croatie",
  "cu":"Cuba",
  "cw":"Curaçao",
  "cy":"Chypre",
  "cz":"République Tchèque",
  "ci":"Côte d'Ivoire",
  "dk":"Danemark",
  "dj":"Djibouti",
  "dm":"Dominique",
  "do":"République Dominicaine",
  "ec":"Equateur",
  "eg":"Egypte",
  "sv":"Salvador",
  "gq":"Guinée équatoriale",
  "er":"Erythrée",
  "ee":"Estonie",
  "sz":"Eswatini",
  "et":"Ethiopie",
  "fk":"Îles Falkland",
  "fo":"Îles Féroé",
  "fj":"Fidji",
  "fi":"Finlande",
  "fr":"France",
  "gf":"Guyane Française",
  "pf":"Polynésie Française",
  "tf":"Terres australes et antarctiques françaises",
  "ga":"Gabon",
  "gm":"Gambie ",
  "ge":"Géorgie",
  "de":"Allemagne",
  "gh":"Ghana",
  "gi":"Gibraltar",
  "gr":"Grèce",
  "gl":"Groenland",
  "gd":"Grenade",
  "gp":"Guadeloupe",
  "gu":"Guam",
  "gt":"Guatemala",
  "gg":"Guernesey",
  "gn":"Guinée",
  "gw":"Guinée-Bissau",
  "gy":"Guyane",
  "ht":"Haïti",
  "hm":"Îles Heard et McDonald",
  "va":"Vatican",
  "hn":"Honduras",
  "hk":"Hong Kong",
  "hu":"Hongrie",
  "is":"Islande",
  "in":"Inde",
  "id":"Indonésie",
  "ir":"Iran",
  "iq":"Irak",
  "ie":"Irland",
  "im":"Île de Man",
  "il":"Israël",
  "it":"Italie",
  "jm":"Jamaïque",
  "jp":"Japon",
  "je":"Jersey",
  "jo":"Jordanie",
  "kz":"Kazakhstan",
  "ke":"Kenya",
  "ki":"Kiribati",
  "kp":"Corée du Nord",
  "kr":"Corée du Sud",
  "xk":"Kosovo",
  "kw":"Koweït",
  "kg":"Kirghizistan",
  "la":"Laos",
  "lv":"Lettonie",
  "lb":"Liban",
  "ls":"Lesotho",
  "lr":"Libéria",
  "ly":"Libye",
  "li":"Liechtenstein",
  "lt":"Lituanie",
  "lu":"Luxembourg",
  "mo":"Macao",
  "mg":"Madagascar",
  "mw":"Malawi",
  "my":"Malaisie",
  "mv":"Maldives",
  "ml":"Mali",
  "mt":"Malte",
  "mh":"Îles Marshall",
  "mq":"Martinique",
  "mr":"Mauritanie",
  "mu":"Maurice",
  "yt":"Mayotte",
  "mx":"Mexique",
  "fm":"Micronésie",
  "md":"Moldavie",
  "mc":"Monaco",
  "mn":"Mongolie",
  "me":"Monténégro",
  "ms":"Montserrat",
  "ma":"Maroc",
  "mz":"Mozambique",
  "mm":"Birmanie",
  "na":"Namibie",
  "nr":"Nauru",
  "np":"Népal",
  "nl":"Pays-Bas",
  "nc":"Nouvelle Calédonie",
  "nz":"Nouvelle Zélande",
  "ni":"Nicaragua",
  "ne":"Niger",
  "ng":"Nigeria",
  "nu":"Niué",
  "nf":"Île Norfolk",
  "mp":"Îles Mariannes du Nord",
  "no":"Norvège",
  "om":"Oman",
  "pk":"Pakistan",
  "pw":"Palaos",
  "ps":"Palestine",
  "pa":"Panama",
  "pg":"Papouasie-Nouvelle-Guinée",
  "py":"Paraguay",
  "pe":"Pérou",
  "ph":"Philippines",
  "pn":"Îles Pitcairn",
  "pl":"Pologne",
  "pt":"Portugal",
  "pr":"Porto Rico",
  "qa":"Qatar",
  "mk":"Macédoine du Nord",
  "ro":"Roumanie",
  "ru":"Russie",
  "rw":"Rwanda",
  "re":"La Réunion",
  "bl":"Saint Barthélemy",
  "sh":"Saint Hélène",
  "kn":"Saint-Christophe-et-Niévès",
  "lc":"Sainte-Lucie",
  "mf":"Saint Martin",
  "pm":"Saint Pierre and Miquelon",
  "vc":"Saint Vincent-et-les-Grenadines",
  "ws":"Samoa",
  "sm":"Saint-Marin",
  "st":"Sao Tomé et Principe",
  "sa":"Arabie Saoudite",
  "sn":"Senegal",
  "rs":"Serbie",
  "sc":"Seychelles",
  "sl":"Sierra Leone",
  "sg":"Singapour",
  "sx":"Saint Martin (partie allemande)",
  "sk":"Slovaquie",
  "si":"Slovénie",
  "sb":"Îles Salomon",
  "so":"Somalie",
  "za":"Afrique du Sud",
  "gs":"Géorgie du Sud et Îles Sandwich du Sud",
  "ss":"Soudan du Sud",
  "es":"Espagne",
  "lk":"Sri Lanka",
  "sd":"Soudan",
  "sr":"Suriname",
  "sj":"Svalbard",
  "se":"Suède",
  "ch":"Suisse",
  "sy":"Syrie",
  "tw":"Taiwan",
  "tj":"Tajikistan",
  "tz":"Tanzanie",
  "th":"Thailande",
  "tl":"Timor-Leste",
  "tg":"Togo",
  "tk":"Tokelau",
  "to":"Tonga",
  "tt":"Trinidad et Tobago",
  "tn":"Tunisie",
  "tr":"Turquie",
  "tm":"Turkménistan",
  "tc":"Îles Turks et Caïques",
  "tv":"Tuvalu",
  "ug":"Ouganda",
  "ua":"Ukraine",
  "ae":"Emirats Arabes Unis",
  "gb":"Royaume-Uni",
  "um":"Îles mineures éloignées des États-Unis",
  "us":"Etats Unis d'Amérique",
  "uy":"Uruguay",
  "uz":"Ouzbékistan",
  "vu":"Vanuatu",
  "ve":"Venezuela",
  "vn":"Vietnam",
  "vg":"Îles Vierges britanniques",
  "vi":"Îles Vierges des États-Unis",
  "wf":"Wallis et Futuna",
  "eh":"Sahara occidental",
  "ye":"Yémen",
  "zm":"Zambie",
  "zw":"Zimbabwe",
  "ax":"Åland"
};
